In [ ]:
#Question 1
'''
Vision: Identify objects and people, and for depth perception
Technology/Frameworks required: Stereo and Depth Cameras
OpenCV for image processing
Tensorflow for facial recognition

Speech: To listen and react back vocally to the humans
Technology/Frameworks required; Microphones to pick up the sound waves
Speakers to output the sound
Kaldi: A toolkit used for speech recognition
NLP models
WaveNet: For speech synthesis

Movement: To physically interact with the outside world
Technology/Frameworks required: Actuators and Motors
LIDAR: to 3D map the enviornment
A* Algorithm: Pathfinding

Learn: To enable a robot to learn from its enviornment
Technology/Frameworks required: Reinforcement Learning: Robot learning from trial and error
Pytorch/Keras : To deploy machine learning models
'''

In [ ]:
#q 2
import pandas as pd
import matplotlib.pyplot as plt

robot_data = pd.read_csv('robot.csv')

print(robot_data['Interaction_Count'].mean())
print(robot_data['Steps_Walked'].sum())
print(robot_data['Energy_Consumption (kWh)'].max())
print(robot_data['Energy_Consumption (kWh)'].min())
print(robot_data['Steps_Walked'].corr(robot_data['Energy_Consumption (kWh)']))
robot_data['Objects_Recognized'].plot(kind='hist')
plt.show()
print(robot_data['Learning_Sessions'].var())

In [8]:
#q 4
name = "TEJA"
age = 19
height = 1.5
is_Female = True
print(f"Name: {name}, Age: {age}, Height: {height}m, Is Female: {is_Female}")

Name: TEJA, Age: 19, Height: 1.5m, Is Female: True


In [ ]:
#Question 3
import pandas as pd
import matplotlib.pyplot as plt
robot_data = pd.read_csv('robot.csv')

print(robot_data[ 'Interaction_Count'].mean())

print(robot_data[ 'Steps_Walked'].sum())

print(robot_data['Energy_ Consumption (kWh)'].max())
print(robot_data['Energy_Consumption (kWh) '].min())

print(robot_data[ Steps Walked'].corr(robot_data["Energy_Consumption (kWh)']))
robot_data[ ‘Objects Recognized'].plot(kind="hist'")

plt.show()
print(robot_data[ 'Learning_Sessions'].var())

In [14]:
num = int(input("Enter a number: "))
if num > 0:
    print("Positive")
elif num < 0:
    print("Negative")
else:
    print("Zero")

<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'PyodideFuture'

Enter a number:  5


In [15]:
num = int(input("Enter a number for multiplication table: "))
for i in range(1, 11):
    print(f"{num} x {i} = {num * i}")

<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'PyodideFuture'

Enter a number for multiplication table:  3


In [18]:
# Q 7
fruits = ["Apple", "Banana", "Cherry", "Mango", "Tomato"]
print(fruits)

# Q 8
numbers = (1, 2, 3, 4, 5)
print(numbers)

# Q 9
students = {"Teja": 85, "Sasi": 90, "Adi": 79}
print(students)

# Q 10
set1 = {1, 2, 3}
set2 = {3, 4, 5}
print(set1)
print(set2)

['Apple', 'Banana', 'Cherry', 'Mango', 'Tomato']
(1, 2, 3, 4, 5)
{'Teja': 85, 'Sasi': 90, 'Adi': 79}
{1, 2, 3}
{3, 4, 5}


In [19]:
def find_largest():
    numbers = []
    for i in range(5):
        num = int(input(f"Enter number {i + 1}: "))
        numbers.append(num)
    
    largest = numbers[0]
    for num in numbers[1:]:
        if num > largest:
            largest = num
            
    return largest

# Example usage
print("The largest number is:", find_largest())


<class 'TypeError'>: int() argument must be a string, a bytes-like object or a real number, not 'PyodideFuture'

Enter number 1:  3


In [20]:
l = []
for x in range(1,21):
    if(x%2==0):
        l.append(x**2)
print(l)
    

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]


In [21]:
import numpy as np
# Q 14
print(np.array([1, 2, 3]).shape)
print(np.array([[1, 2], [3, 4]]).shape)
print(np.array([[[1], [2]], [[3], [4]]]).shape)

# Q 15
print(np.random.randint(1, 100, (5, 5)))

# Q 16
print(np.arange(1, 17).reshape(4, 4)[:, 1:3])

# Q 17
print(np.arange(12).reshape(6, 2).reshape(2, 3, 2).flatten())

# Q 18
print(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) + np.array([1, 2, 3]))

# Q 19
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
print(A + B)
print(A - B)
print(A * B)
print(A / B)


(3,)
(2, 2)
(2, 2, 1)
[[29 39 47 78 95]
 [10 15 85 87 31]
 [45 95 57 22 75]
 [48 86 14 95 30]
 [43 37 74 54 40]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [24]:
import pandas as pd
data = {
    'Name': ['Teja', 'Sasi', 'Adi'],
    'Math': [85, 88, 92],
    'Science': [100, 88, 99],
    'English': [75, 10, 100]
}

df = pd.DataFrame(data)
df['Total'] = df['Math'] + df['Science'] + df['English']
def assign_grade(total):
    if total >= 270:
        return 'A'
    elif total >= 240:
        return 'B'
    elif total >= 210:
        return 'C'
    else:
        return 'D'
df['Grade'] = df['Total'].apply(assign_grade)
print(df)



   Name  Math  Science  English  Total Grade
0  Teja    85      100       75    260     B
1  Sasi    88       88       10    186     D
2   Adi    92       99      100    291     A
